# Generated by Django 3.0.8 on 2020-08-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200802_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        
    ]
