# Generated by Django 3.0.8 on 2020-08-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200802_0749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useractivity',
            old_name='in_time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='useractivity',
            old_name='out_time',
            new_name='end_time',
        ),
       
    ]
